name: Deploy on DockerHub Push

on:
  repository_dispatch:
    types: [dockerhub_push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan jesugo-aubin.nounagnon.takima.cloud >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: ansible-playbook -i inventories/setup.yml deploy.yml
